ETrade.WebMvcUI/Models/CategoryListViewModel.cs
using ETrade.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETrade.WebMvcUI.Models
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }

    }
}

ETrade.WebMvcUI/Models/ProductListViewModel.cs
using ETrade.Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETrade.WebMvcUI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

ETrade.WebMvcUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETrade.BusinessLayer.Abstract;
using ETrade.WebMvcUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.WebMvcUI.Controllers
{
    public class HomeController : Controller
    {
        private IProductService _productService;
        public HomeController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int page = 1, int category = 0)
        {
            int pageSize = 10;
            var products = _productService.GetByCategory(category);
            ProductListViewModel model = new ProductListViewModel()
            {
                Products = products.Skip((page - 1) * pageSize).Take(pageSize).ToList()
            };

            return View(model);
        }
    }
}

ETrade.WebMvcUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ETrade.BusinessLayer.Abstract;
using ETrade.WebMvcUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ETrade.WebMvcUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public ActionResult Index()
        {
            var result = _productService.GetAll();

            ProductListViewModel model = new ProductListViewModel
            {
                Products = result
            };

            return View(model);
        }
    }
}

ETrade.WebMvcUI/ViewComponents/CategoryListViewComponent.cs
using ETrade.BusinessLayer.Abstract;
using ETrade.WebMvcUI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ETrade.WebMvcUI.ViewComponents
{
    public class CategoryListViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var categoryList = _categoryService.GetAll();

            CategoryListViewModel model = new CategoryListViewModel()
            {
                Categories = categoryList,
                CurrentCategory=Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

ETrade.WebMvcUI/Views/Home/Index.cshtml
@model ETrade.WebMvcUI.Models.ProductListViewModel
@{
    ViewData["Title"] = "Index";
}

<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="1"></li>
                        <li data-target="#slider-carousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        <div class="item active">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>Free E-Commerce Template</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="/images/home/girl1.jpg" class="girl img-responsive" alt="" />
                                <img src="/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>
                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>100% Responsive Design</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="/images/home/girl2.jpg" class="girl img-responsive" alt="" />
                                <img src="/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>

                        <div class="item">
                            <div class="col-sm-6">
                                <h1><span>E</span>-SHOPPER</h1>
                                <h2>Free Ecommerce Template</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                <button type="button" class="btn btn-default get">Get it now</button>
                            </div>
                            <div class="col-sm-6">
                                <img src="/images/home/girl3.jpg" class="girl img-responsive" alt="" />
                                <img src="/images/home/pricing.png" class="pricing" alt="" />
                            </div>
                        </div>

                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->

<section>
    <div class="container">
        <div class="row">
            @await Component.InvokeAsync("CategoryList")
            <div class="col-sm-9 padding-right">
                <div class="features_items">
                    <!--features_items-->
                    <h2 class="title text-center">ÜRÜNLER</h2>
                    @foreach (var products in Model.Products)
                    {

                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <img src="/images/home/product.jpg" alt="" />
                                        <h2>@products.UnitPrice</h2>
                                        <p>@products.ProductName</p>
                                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Sepete Ekle</a>
                                    </div>
                                    <div class="product-overlay">
                                        <div class="overlay-content">
                                            <h2>@products.UnitPrice</h2>
                                            <p>@products.ProductName</p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-de"></i>Ürün Detay</a>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Sepete Ekle</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

ETrade.WebMvcUI/Views/Product/Index.cshtml
@model ETrade.WebMvcUI.Models.ProductListViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Product Index</h1>

<table class="table table-hover">
    <thead class="">
        <tr>
            <th>Product Name</th>
            <th>Unit Price</th>
            <th>Units In Stock</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
            <tr>
                <td>@product.ProductName</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
            </tr>
        }
    </tbody>
</table>

ETrade.WebMvcUI/Views/Shared/Components/CategoryList/Default.cshtml
@model ETrade.WebMvcUI.Models.CategoryListViewModel

    <div class="col-sm-3">
        <div class="left-sidebar">
            <h2>KATEGORİLER</h2>
            <div class="panel-group category-products" id="accordian">
                <!--category-productsr-->

                @foreach (var categories in Model.Categories)
                {
                    //var css = "panel-title";
                    //if (categories.CategoryId==Model.CurrentCategory)
                    //{
                    //    css += " active";
                    //}

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><a href="/Home/Index?category=@categories.CategoryId"><b>@categories.CategoryName</b></a></h4>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>